### ISSUE TITLE
circleci & travis alignment & continuity

### ISSUE THREAD

**Issue by dakkusingh** [Lullabot/drupal8ci#22]
Just seen @juampynr recent push with Travis. Great work first of all.
https://github.com/Lullabot/drupal8ci/blob/master/dist/travisci/.travis/docker-compose.yml

In some ways I quite like that it is using Wodby images. I also use Wodby for production stack, and their dinky image size is always a plus (Alpine).

It does however mean that:
1) should we re-jig drupal8ci to use wodby instead of drupal-apache (official docker) images? Wodby uses Alpine and therefore images are much smaller.
2) should we re-jig circleci flow to closely align with travis?

Needs some food for thought!! What do you guys think?

**Comment by deviantintegral** [comment]
Part of the original intent in using only "official" images was the assumption that many users coming to this would be using Docker for the first time. If you need to customize an image (such as adding a php extension), having alpine with a different package manager is an additional tool to learn. But, perhaps that's less important now.

Figuring out how simple adding an extension (bcmath is a good one) from apk or pecl would be a good test.

We're aiming as much as possible to share testing configurations and make the service-specific files like `.travis.yml` as thin as possible. That way, the risk of having to change CI tools is reduced. I'd actually be interested in seeing what happens if we stop using Circle's native docker functionality, and use docker-compose everywhere instead.

**Comment by dakkusingh** [comment]
Thanks @deviantintegral - I will make a couple of pull requests to share efforts :D
